### PR TITLE
Implement About Menu and Version Dialog

### LINKED ISSUE #44: Show current version in application menu
Once we implemented #43, we could show the local version of Excalidraw the application menu

### PR DESCRIPTION
**Pull request by shrirambalaji**
What does this PR do?

- Adds an Excalidraw Menu Item and About Dialog (https://github.com/excalidraw/excalidraw-desktop/issues/44)
- Adds a metadata store
- Adds a preload script, for exposing main process apis to renderer.
- Converts node requires to typescript style imports.
- Adds a constants file

### CODE REVIEW

**Review by pinussilvestrus — COMMENTED** [review]
Thanks for the contribution! @lipis let's add @Shriram-Balaji as a contributor so he does not have to fork thee project to create PRs :)

one thing: on my device (macOS) the about dialog has a malformed position (when I made the app fullscreen):

image

That's why I am not able to close it.

**Comment by pinussilvestrus** [comment]
Another thing: 
image

In the built distro version the dialog throws some errors and is not displayed. Seems like we have to [store some stuff in the distro](https://github.com/excalidraw/excalidraw-desktop/blob/master/electron-builder.json)

**Comment by shrirambalaji** [comment]
@pinussilvestrus I've fixed the electron-builder. Also added a `.center` to the about window panel, so it should ideally fix it on mac. If it doesn't we can consider making the AboutWindow separate, and not as a child of the mainBrowserWindow ( so that we can atleast get it closed ).

Also, I believe the way Menu items are ordered, is quite different based on OS. Linux and Windows Apps seem to have the `About` section under Help, for eg. Slack on Linux. We can probably do that in a separate PR, discussing what else needs to be added / removed in the Menu.

slack-about

**Comment by pinussilvestrus** [comment]
Still not showing correctly: 

Bildschirmfoto 2020-04-17 um 13 41 52

> I believe the way Menu items are ordered, is quite different based on OS

That's the case, yeah. But +1 do discuss that in a separate issue to have it in an orderly manner.

**Comment by shrirambalaji** [comment]
I'm starting to think the position issue is because the about window is bound to actual one. I think we can make it a separate window.

**Comment by pinussilvestrus** [comment]
Let's try it out 🚀

**Comment by shrirambalaji** [comment]
@pinussilvestrus I think the centering issue should be fixed.

**Comment by pinussilvestrus** [comment]
That's good!

Another thing I experienced, is that it seems to add a new menu every time I open it, which resolves in a lot of new Menu entries.

image

At the start, it has two application menus, the first one seems to be a bug

image

**Comment by shrirambalaji** [comment]
Weirdly, I cannot reproduce both the bugs mentioned above on linux, but I made a change to call setupMenu once when the app's main window loads which should atlease fix the first issue that you see.

**Comment by pinussilvestrus** [comment]
It seems to be Mac related to creating the application menu twice. Maybe I can have a look at the weekend.

**Comment by shrirambalaji** [comment]
@pinussilvestrus I think I know why the bug on mac is happening. So I've made a fix for the menu-items specific to mac and as mentioned above, I have moved the About section to Help for other platforms. Let me know if you can still reproduce it.

image

**Review by pinussilvestrus — APPROVED** [review]
Works like a charm now 🚀 

Let's merge it and investigate sorting the menu entries in another issue.

**Comment by pinussilvestrus** [comment]
@lipis would it be possible to add @Shriram-Balaji to the desktop-team?

**Pull request merged**
